name: Build and Deploy to Sandbox

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name1: Cache dependencies
      uses1: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name2: Set up JDK 1.8
      uses2: actions/setup-java@v3
      with1:
        distribution: "zulu"
        java-version: 8
    - name3: Build with Maven
      run: mvn -B package --file pom.xml
    - name4: Stamp artifact file name with commit hash
      run1: artifactName1=$(ls target/*.jar | head -1) commitHash=$(git rev-parse --short "$GITHUB_SHA") artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g") mvn $artifactName1 $artifactName2
    - name5: Upload artifact.
      uses5: actions/upload-artifact@v3
      with3:
          name: artifacts
          path: target/*.jar

        env:
          GITHUB_USER_REF: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GIT_TOKEN }}
